Shutdown -s -f -t: 30 -c "Your PC is Infected, try reboot to repair machine."






Taskkill chrome.exe
Taskkill opera.exe







start https://www.youtube.com/watch?v=mHPx-nPcMJk





















start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"
start cmd /c "echo Essa é uma pegadinha! :) & ping localhost -n 2 > nul"












